language: cpp
jobs:
  include:
#Linux
    - stage: Build
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      if: branch = master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - USE_COVERAGE="ON"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - USE_WS="ON"
      workspaces:
        create:
          name: linux-binaries
          paths:
            - out/

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

# Windows
    - os: windows
      env:
        - USE_WS="ON"
      workspaces:
        create:
          name: windows-binaries
          paths:
            - out/

# Macos
    - os: osx
      osx_image: xcode11.2
      env:
        - USE_WS="ON"
      workspaces:
        create:
          name: osx-binaries
          paths:
            - out/

    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4

# Deploy stage
    - stage: Deployment
      language: csharp
      mono: none
      dotnet: 3.1
      os: windows # We use Windows to easier make use of the dotnet environment for nuget
      workspaces:
        use:
          - linux-binaries
          - windows-binaries
          - osx-binaries
      before_script:
        - cd src/wrapper/csharp
        - dotnet restore
      script:
        - dotnet build
        - dotnet pack
      after_success: 
        - dotnet nuget push FAIL --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - if [[ $USE_COVERAGE ]]; then lcov --directory . --zerocounters; fi
  - if [[ $TRAVIS_OS_NAME != "windows" ]]; then export CXXFLAGS="-Wall -Wextra -Werror -Wpedantic"; fi
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/out/${TRAVIS_OS_NAME}" ..
script:
  - cmake --build . 
after_success:
  - ctest -C Debug --output-on-failure
  - if [[ $USE_COVERAGE ]]; then make coveralls; fi
  - if [[ $USE_WS ]]; then cmake --install . ; fi
notifications:
  email: false
