set(CPACK_PACKAGE_VENDOR "PearCoding")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Tiny parser for project files used by Mitsuba raytracer")
set(CPACK_PACKAGE_CONTACT "PearCoding <omercan AT pearcoding DOT eu>")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_SOURCE_IGNORE_FILES
    /.vscode
    /.git
    /dist
    /.*build.*
    /\\\\.DS_Store
)

include(CPack)